package = "nvimpack-selector"
version = "0.1.0"
lua = ">=5.1"

[description]
summary = "A simple ui for vim.pack"
maintainer = "pablohernandezm"
labels = [ "neovim" ]
license = "MIT"

[dependencies]
# Add your dependencies here

[test]
type = "busted"

[build]
type = "builtin"
