name: Setup Neovim and Lux
description: 'Set up Neovim and install Lux'
inputs:
  nvim-version:
    required: true
runs:
  using: "composite"
  steps:
    - uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: ${{ inputs.nvim-version }}
    - uses: lumen-oss/gh-actions-lux@v1
      with:
        version: 0.30.2
